### ISSUE TITLE
please add picture of THETA X

### ISSUE THREAD

**Issue by jcasman** [theta360developers/tasker-guide#2]
Please add a picture of RICOH THETA X. You can use this image here: https://theta360.com/intl/about/theta/img/img_x_share.png  

Probably shrink and/or crop the image to fit better

**Comment by codetricity** [comment]
Looks like it is completed

![image](https://user-images.githubusercontent.com/5799860/223214059-8bcb9f58-b80a-4a65-b5e9-24b05210f0df.png)

![image](https://user-images.githubusercontent.com/5799860/223214224-3d2b7737-1cbf-43af-8e62-63385e902587.png)
