### ISSUE TITLE
Delete theta360.guide icon (green circle) from list of icons at top of article

### ISSUE THREAD

**Issue by jcasman** [theta360developers/tasker-guide#3]
I think it's unclear what the theta360.guide icon (green circle) does in the list of icons at the top of the article. Please delete.

**Comment by codetricity** [comment]
![Screen Shot 2023-03-06 at 11 44 53](https://user-images.githubusercontent.com/5799860/223214425-f163b401-ede1-4168-8f24-400b4287074a.png)
