### ISSUE TITLE
Add Tasker Share link to Resources section

### ISSUE THREAD

**Issue by jcasman** [theta360developers/tasker-guide#5]
Add your Tasker Share for [Info and State](https://taskernet.com/shares/?user=AS35m8kajU17RlSqYXioAiOHtz3ZH5t63ZQqxoCjEdiCgDA2BoPfS9yYJ9gHtpObgWBbv9I%3D&id=Task%3AInfo+And+State) to the Resources section. Possibly add an explanation of what it is.

**Comment by codetricity** [comment]
looks good
